<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGhylsnd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGhylsnd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGhylsnd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGhylsnd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGhylsnd\appProdProjectContainer(array(
    'container.build_hash' => 'Ghylsnd',
    'container.build_id' => '8ffe23ae',
    'container.build_time' => 1544042641,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGhylsnd');
