<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVpbh5c2\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVpbh5c2/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVpbh5c2.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVpbh5c2\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVpbh5c2\appProdProjectContainer(array(
    'container.build_hash' => 'Vpbh5c2',
    'container.build_id' => '0811960a',
    'container.build_time' => 1544984626,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVpbh5c2');
