<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXgj52sv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXgj52sv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXgj52sv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXgj52sv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXgj52sv\appProdProjectContainer(array(
    'container.build_hash' => 'Xgj52sv',
    'container.build_id' => '04205f48',
    'container.build_time' => 1544560365,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXgj52sv');
