<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxb2426\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxb2426/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGxb2426.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGxb2426\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGxb2426\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Gxb2426',
    'container.build_id' => 'c3946242',
    'container.build_time' => 1544566964,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxb2426');
