<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2sd7vxo\appDevProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2sd7vxo/appDevProjectContainer.php') {
    touch(__DIR__.'/Container2sd7vxo.legacy');

    return;
}

if (!\class_exists(appDevProjectContainer::class, false)) {
    \class_alias(\Container2sd7vxo\appDevProjectContainer::class, appDevProjectContainer::class, false);
}

return new \Container2sd7vxo\appDevProjectContainer(array(
    'container.build_hash' => '2sd7vxo',
    'container.build_id' => 'd4cee292',
    'container.build_time' => 1544042768,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2sd7vxo');
